micronaut:
  application:
    name: paymaster
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
    redirect:
      enabled: false
    oauth2:
      clients:
        iam:
          client-id: "${CLIENT_ID}"
          client-secret: "${CLIENT_SECRET}"
          grant-type: client_credentials
          token:
            url: "${TOKEN_URL}"
            auth-method: client_secret_basic
  server:
    netty:
      access-logger:
        enabled: true
    port: ${PORT:8082}
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    dialect: postgres
    url: "jdbc:postgresql://localhost:5432/paymaster"
    username: "paymaster"
    password: "paymaster"
    maximum-pool-size: 5
    schema-generate: none
netty:
  default:
    allocator:
      max-order: 3
jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss
  time-zone: UTC
iam:
  api:
    host: "${IAM_URL}"
